version: "1.0"

stages:
  - setup
  - build
  - deploy

steps:
  setup:
    - name: Prepare Environment
      image: alpine:3.15
      commands:
        - echo "Setting up environment variables..."
        - export APP_ENV="production"

  build:
    - name: Build Application
      image: php:8.1-cli
      commands:
        - echo "Installing dependencies..."

  deploy:
    - name: Deploy Application
      image: php:8.1-cli
      commands:
        - echo "Starting deployment process..."


variables:
  ENV_FILE: ".env"
  DEPLOY_DIR: "/var/www/html"

hooks:
  before:
    - name: Validate Configuration
      image: alpine:3.15
      commands:
        - echo "Checking configuration..."


  after:
    - name: Notify Success
      image: alpine:3.15
      commands:
        - echo "Deployment notification sent!"

